### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by sarendis56** [moemode/xv6-labs-2023#1]
Hi, may I ask how do you download this repository from MIT. I try many times and I can clone from github smoothly, but neither can I ping g.csail.mit.edu nor can I use `git clone git://g.csail.mit.edu/xv6-labs-2023` as specified by the homepage of 6.828.

❯ git clone git://g.csail.mit.edu/xv6-labs-2023
Cloning into 'xv6-labs-2023'...
fatal: unable to connect to g.csail.mit.edu:
g.csail.mit.edu[0: 128.52.128.187]: errno=Operation timed out

Many thanks!

**Comment by moemode** [comment]
I think it was just a temporary issue. I can clone it, tried right now. Does it work for you now?

**Comment by sarendis56** [comment]
> I think it was just a temporary issue. I can clone it, tried right now. Does it work for you now?

Yes, I just tried and it succeeds! Thanks a lot. I was just afraid that I got stuck on the first step :)

**Comment by sarendis56** [comment]
> I think it was just a temporary issue. I can clone it, tried right now. Does it work for you now?

Just tried and it got stuck and failed near success again... I think it's just my network connection issue or something. Thank you anyway!
